# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_CONFIG "Release")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/Asus/Downloads/zenoh-c-main;C:/Users/Asus/Downloads/zenoh-c-main/build_mingw")
set(CPACK_CMAKE_GENERATOR "MinGW Makefiles")
set(CPACK_CMAKE_SYSTEM_PROCESSOR "AMD64")
set(CPACK_COMPONENTS_ALL "dev;headers;lib")
set(CPACK_COMPONENT_DEV_DEPENDS "lib")
set(CPACK_COMPONENT_DEV_DESCRIPTION "The C client library for Eclipse zenoh - zenoh-c static lib and cmake files")
set(CPACK_COMPONENT_DEV_GROUP "dev")
set(CPACK_COMPONENT_HEADERS_DEPENDS "lib")
set(CPACK_COMPONENT_HEADERS_DESCRIPTION "The C client library for Eclipse zenoh - header files")
set(CPACK_COMPONENT_HEADERS_GROUP "dev")
set(CPACK_COMPONENT_LIB_DESCRIPTION "The C client library for Eclipse zenoh")
set(CPACK_COMPONENT_LIB_GROUP "lib")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "AMD64-Windows")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Users/Asus/Downloads/mingw64/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "zenohc built using CMake")
set(CPACK_GENERATOR "7Z;ZIP")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALLED_DIRECTORIES "C:/Users/Asus/Downloads/zenoh-c-main;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/zenohc")
set(CPACK_MODULE_PATH "C:/Users/Asus/Downloads/zenoh-c-main/cmake")
set(CPACK_NSIS_DISPLAY_NAME "zenohc 1.9.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "zenohc 1.9.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "C:/Users/Asus/Downloads/mingw64/bin/objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "C:/Users/Asus/Downloads/mingw64/bin/objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/CPackConfig.cmake")
set(CPACK_PACKAGE_CHECKSUM "MD5")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Users/Asus/Downloads/mingw64/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "The C bindings for Zenoh")
set(CPACK_PACKAGE_DIRECTORY "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/packages")
set(CPACK_PACKAGE_FILE_NAME "zenohc-1.9.0-Source")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/eclipse-zenoh/zenoh-c")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "zenohc 1.9.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "zenohc 1.9.0")
set(CPACK_PACKAGE_NAME "zenohc")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "The Eclipse Foundation")
set(CPACK_PACKAGE_VERSION "1.9.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "9")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "C:/Users/Asus/Downloads/zenoh-c-main/install/cpack_project_config.cmake")
set(CPACK_READELF_EXECUTABLE "C:/Users/Asus/Downloads/mingw64/bin/readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/Asus/Downloads/mingw64/share/cmake-4.3/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "C:/Users/Asus/Downloads/mingw64/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Users/Asus/Downloads/mingw64/share/cmake-4.3/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_ARCHITECTURE "AMD64")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "C:/Users/Asus/Downloads/zenoh-c-main;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "zenohc-1.9.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "win64-Source")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
