# CMake generated Testfile for 
# Source directory: C:/Users/Asus/Downloads/zenoh-c-main/tests
# Build directory: C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_z_api_alignment_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_alignment_test.exe")
set_tests_properties(unit_z_api_alignment_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_config_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_config_test.exe")
set_tests_properties(unit_z_api_config_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_constants "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_constants.exe")
set_tests_properties(unit_z_api_constants PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_double_drop_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_double_drop_test.exe")
set_tests_properties(unit_z_api_double_drop_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_drop_options "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_drop_options.exe")
set_tests_properties(unit_z_api_drop_options PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_encoding_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_encoding_test.exe")
set_tests_properties(unit_z_api_encoding_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_info "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_info.exe")
set_tests_properties(unit_z_api_info PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_keyexpr_drop_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_keyexpr_drop_test.exe")
set_tests_properties(unit_z_api_keyexpr_drop_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_keyexpr_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_keyexpr_test.exe")
set_tests_properties(unit_z_api_keyexpr_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_liveliness "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_liveliness.exe")
set_tests_properties(unit_z_api_liveliness PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_null_drop_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_null_drop_test.exe")
set_tests_properties(unit_z_api_null_drop_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_payload_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_payload_test.exe")
set_tests_properties(unit_z_api_payload_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_session_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_session_test.exe")
set_tests_properties(unit_z_api_session_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(unit_z_api_unitinialized_check "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_api_unitinialized_check.exe")
set_tests_properties(unit_z_api_unitinialized_check PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(build_z_build_shared "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_build_shared.exe")
set_tests_properties(build_z_build_shared PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(integration_z_int_helpers_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_int_helpers_test.exe")
set_tests_properties(integration_z_int_helpers_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(integration_z_int_pub_sub_attachment_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_int_pub_sub_attachment_test.exe")
set_tests_properties(integration_z_int_pub_sub_attachment_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(integration_z_int_pub_sub_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_int_pub_sub_test.exe")
set_tests_properties(integration_z_int_pub_sub_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(integration_z_int_queryable_attachment_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_int_queryable_attachment_test.exe")
set_tests_properties(integration_z_int_queryable_attachment_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
add_test(integration_z_int_queryable_test "C:/Users/Asus/Downloads/zenoh-c-main/build_mingw/release/target/release/tests/z_int_queryable_test.exe")
set_tests_properties(integration_z_int_queryable_test PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;67;add_test;C:/Users/Asus/Downloads/zenoh-c-main/tests/CMakeLists.txt;0;")
